# Configuración de importación desde GENSPARK
# Define reglas de mapeo y exclusiones para sincronizar contenido externo

version: 1

# Rutas de destino dentro del repo actual y sus fuentes relativas
# Si no se especifica, se preserva la estructura original de la fuente
mappings:
  # Ejemplos de mapeo (activa los que necesites)
  # - from: backend/
  #   to: backend/
  # - from: docs/
  #   to: docs/
  # - from: docker/
  #   to: docker/
  # - from: supabase/
  #   to: supabase/
  # - from: frontend/
  #   to: frontend/

# Exclusiones comunes al importar (patrones rsync)
exclude:
  - .git/
  - node_modules/
  - dist/
  - build/
  - .vscode/
  - .vscode-server/
  - .idea/
  - logs/
  - *.log
  - tmp/
  - temp/
  - .env
  - .env.*
  - *.Zone.Identifier

# Comportamiento
options:
  overwrite: true        # Sobrescribir archivos si cambian
  delete_extraneous: false # No borrar archivos que no existan en la fuente
  preserve_times: true
  preserve_perms: true
  dry_run_default: true    # Por defecto, mostrar diff sin escribir
