#!/bin/bash

# Script para ejecutar las migraciones SQL en Supabase
# Necesita tener los archivos SQL locales

echo "🔧 Script para ejecutar SQL en Supabase"
echo "======================================="
echo ""
echo "⚠️  IMPORTANTE: Debes ejecutar estos pasos MANUALMENTE en Supabase Dashboard"
echo ""
echo "📋 PASO 1: Schema (Crear Tablas)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Ve a: https://supabase.com/dashboard"
echo "2. Selecciona proyecto: htvlwhisjpdagqkqnpxg"
echo "3. Click en 🔧 'SQL Editor' (menú izquierdo)"
echo "4. Click en 'New query'"
echo "5. Copia COMPLETAMENTE el siguiente SQL:"
echo ""
echo "─────────────────────────────────────────────────────────────────"
cat /home/eevan/ProyectosIA/SIST_PIZZA/supabase/migrations/20250115000000_initial_schema.sql
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "6. Pégalo en el SQL Editor y click en 'Run' (Ctrl+Enter)"
echo "7. Deberías ver: ✅ 'Success. No rows returned'"
echo ""
echo ""
echo "📋 PASO 2: Seed Data (Insertar Datos)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click en 'New query' nuevamente"
echo "2. Copia COMPLETAMENTE el siguiente SQL:"
echo ""
echo "─────────────────────────────────────────────────────────────────"
cat /home/eevan/ProyectosIA/SIST_PIZZA/supabase/migrations/20250115000001_seed_data.sql
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "3. Pégalo en el SQL Editor y click en 'Run'"
echo "4. Deberías ver: ✅ 'Success. No rows returned'"
echo ""
echo ""
echo "✅ Después de ejecutar ambos scripts:"
echo "   1. Las 6 tablas estarán creadas"
echo "   2. 25+ registros de prueba insertados"
echo "   3. Backend podrá conectarse a Supabase"
echo "   4. El health check mostrará: database: ok ✅"
echo ""
