global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# Plantilla de notificaciones
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Ruta de notificaciones
route:
  group_by: ['alertname', 'severity', 'component']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3h
  receiver: 'default-receiver'
  
  routes:
    # Alertas críticas a múltiples canales
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    
    # Alertas de negocio
    - match:
        component: business
      receiver: 'business-alerts'
    
    # Alertas de base de datos
    - match:
        component: database
      receiver: 'database-alerts'
    
    # Alertas de Redis
    - match:
        component: redis
      receiver: 'redis-alerts'
    
    # Alertas de integraciones
    - match:
        component: integrations
      receiver: 'integration-alerts'

# Receptores de alertas
receivers:
  - name: 'default-receiver'
    slack_configs:
      - channel: '#sist-pizza-alerts'
        title: '{{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Component:* {{ .Labels.component }}
          {{ end }}
        send_resolved: true

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#sist-pizza-critical'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Component:* {{ .Labels.component }}
            *Status:* {{ .Status }}
          {{ end }}
        send_resolved: true
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    
    # PagerDuty para alertas críticas (opcional)
    # pagerduty_configs:
    #   - service_key: '${PAGERDUTY_SERVICE_KEY}'
    #     description: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }}'

  - name: 'business-alerts'
    slack_configs:
      - channel: '#sist-pizza-business'
        title: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
          {{ end }}

  - name: 'database-alerts'
    slack_configs:
      - channel: '#sist-pizza-database'
        title: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
          {{ end }}

  - name: 'redis-alerts'
    slack_configs:
      - channel: '#sist-pizza-cache'
        title: '🔴 Redis Alert: {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
          {{ end }}

  - name: 'integration-alerts'
    slack_configs:
      - channel: '#sist-pizza-integrations'
        title: '🔗 Integration Alert: {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
          {{ end }}

# Configuración de inhibición
inhibit_rules:
  # Si el servicio está caído, no alertar sobre latencia
  - source_match:
      severity: 'critical'
      alertname: 'BackendDown'
    target_match:
      severity: 'warning'
    equal: ['component']
  
  # Si hay alta tasa de error, no alertar sobre latencia
  - source_match:
      alertname: 'CriticalErrorRate'
    target_match:
      alertname: 'HighLatency'
    equal: ['component']
