global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sist-pizza-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API metrics
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL exporter (via prometheuscommunity/postgres-exporter)
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter (via oliver006/redis_exporter)
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    honor_timestamps: true
    scrape_interval: 30s
